-- 코드를 입력하세요
SELECT DISTINCT R.FOOD_TYPE FOOD_TYPE, R.REST_ID REST_ID, R.REST_NAME REST_NAME, F.MAX_FA FAVORITES
FROM REST_INFO R
JOIN (
    SELECT DISTINCT FOOD_TYPE, MAX(FAVORITES) MAX_FA
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) F ON R.FOOD_TYPE = F.FOOD_TYPE AND  R.FAVORITES = F.MAX_FA
ORDER BY FOOD_TYPE DESC;
