-- 코드를 입력하세요 
WITH hours AS (
    SELECT 9 AS HOUR
    UNION ALL SELECT 10
    UNION ALL SELECT 11
    UNION ALL SELECT 12
    UNION ALL SELECT 13
    UNION ALL SELECT 14
    UNION ALL SELECT 15
    UNION ALL SELECT 16
    UNION ALL SELECT 17
    UNION ALL SELECT 18
    UNION ALL SELECT 19
)

SELECT H.HOUR, COUNT(ANIMAL_ID) COUNT
FROM ANIMAL_OUTS A RIGHT JOIN hours H ON HOUR(A.DATETIME) = H.HOUR
GROUP BY H.HOUR;