SELECT Y.YEAR AS YEAR, Y.MAX_SIZE- E.SIZE_OF_COLONY AS YEAR_DEV, E.ID AS ID
FROM ECOLI_DATA E JOIN (  
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) Y ON YEAR(DIFFERENTIATION_DATE) = Y.YEAR
ORDER BY Y.YEAR, Y.MAX_SIZE- E.SIZE_OF_COLONY;