-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK B JOIN (
    SELECT *
    FROM BOOK_SALES
    WHERE YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '01'
    ) S  
ON B.BOOK_ID = S.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;